version: "3"
services:
  app:
    build: .
    container_name: go-api
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: 'go run cmd/api/main.go'
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=c
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
    volumes:
      - "mysqldb:/var/lib/mysql"

volumes:
  mysqldb: